Event crud
mburko/planex-be pull request #5
Opened 2022-11-04 21:24 UTC by Hello-Own-World

Event crud, responsible for events and user_events in DB

2022-11-09 16:20 UTC, andrii-tar submitted a review, later dismissed
I suggest to add some data validation, everything else is OK

2022-11-10 08:07 UTC, andrii-tar requested changes
Temporary comment redirect response in delete event it can cause FE troubles, and add check if start date is before finish

2022-11-22 08:46 UTC, andrii-tar approved these changes
Approved

2022-11-22 08:51 UTC, KovalBohdann approved these changes

2022-11-22 08:52 UTC, merged